/*
 * JS for BibleMovie generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4b464740-e86b-4924-8e09-04c561d6fb19';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "BibleMovie",
    "location": "BibleMovie.html"
}];

function BibleMovie_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'BibleMovie_mobilebutton_2',
        'youtube_3': 'BibleMovie_youtube_3',
        'youtube_4': 'BibleMovie_youtube_4',
        'youtube_5': 'BibleMovie_youtube_5',
        'mobilebutton_14': 'BibleMovie_mobilebutton_14',
        'mobilelabel_15': 'BibleMovie_mobilelabel_15'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'BibleMovie';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var BibleMovie_onLoad = function() {
            BibleMovie_elementsExtraJS();

            BibleMovie_deviceEvents();
            BibleMovie_windowEvents();
            BibleMovie_elementsEvents();
        };

    // screen window events


    function BibleMovie_windowEvents() {

        $('#BibleMovie').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function BibleMovie_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function BibleMovie_elementsExtraJS() {
        // screen (BibleMovie) extra code

        Apperyio.registerYoutubeComponent("BibleMovie_youtube_3");

        Apperyio.registerYoutubeComponent("BibleMovie_youtube_4");

        Apperyio.registerYoutubeComponent("BibleMovie_youtube_5");

    };

    // screen elements handler


    function BibleMovie_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#BibleMovie_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#BibleMovie_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '#BibleMovie_mobilecontainer [name="mobilebutton_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.top.location = 'https://www.youtube.com/results?q=bible+movies';

                }
            },
        }, '#BibleMovie_mobilecontainer [name="mobilebutton_14"]');

    };

    $(document).off("pagebeforeshow", "#BibleMovie").on("pagebeforeshow", "#BibleMovie", function(event, ui) {
        Apperyio.CurrentScreen = "BibleMovie";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    BibleMovie_onLoad();
};

$(document).off("pagecreate", "#BibleMovie").on("pagecreate", "#BibleMovie", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BibleMovie_js();
});