/*
 * JS for Screen1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4b464740-e86b-4924-8e09-04c561d6fb19';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "BibleMovie",
    "location": "BibleMovie.html"
}];

function Screen1_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_8': 'Screen1_mobilebutton_8',
        'mobilelabel_2': 'Screen1_mobilelabel_2',
        'mobileimage_3': 'Screen1_mobileimage_3',
        'mobilebutton_4': 'Screen1_mobilebutton_4',
        'mobileimage_5': 'Screen1_mobileimage_5',
        'mobilebutton_6': 'Screen1_mobilebutton_6',
        'mobilelabel_9': 'Screen1_mobilelabel_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Screen1';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Screen1_onLoad = function() {
            Screen1_elementsExtraJS();

            Screen1_deviceEvents();
            Screen1_windowEvents();
            Screen1_elementsEvents();
        };

    // screen window events


    function Screen1_windowEvents() {

        $('#Screen1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Screen1_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Screen1_elementsExtraJS() {
        // screen (Screen1) extra code

    };

    // screen elements handler


    function Screen1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Screen1_mobileheader [name="mobilebutton_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        }, '#Screen1_mobileheader [name="mobilebutton_8"]');

        $(document).off("click", '#Screen1_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.top.location = 'http://biblehub.com/niv/m/genesis/1.htm';

                }
            },
        }, '#Screen1_mobilecontainer [name="mobilebutton_4"]');

        $(document).off("click", '#Screen1_mobilecontainer [name="mobilebutton_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.top.location = 'http://biblehub.com/niv/m/genesis/1.htm';

                }
            },
        }, '#Screen1_mobilecontainer [name="mobilebutton_6"]');

    };

    $(document).off("pagebeforeshow", "#Screen1").on("pagebeforeshow", "#Screen1", function(event, ui) {
        Apperyio.CurrentScreen = "Screen1";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Screen1_onLoad();
};

$(document).off("pagecreate", "#Screen1").on("pagecreate", "#Screen1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Screen1_js();
});